06/04/2024 03:55:50 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000203EB82AB40>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 03:55:51 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000203EB82B1A0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 03:55:52 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000203EB88C140>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 03:55:55 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000203EB88C4D0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 03:55:56 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000203EB88C680>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 03:56:06 PM - INFO - root : Starting the test_login_valid_data_functionality
06/04/2024 03:56:19 PM - INFO - root : Login successfully
06/04/2024 03:56:47 PM - INFO - root : Logout successfully
06/04/2024 03:56:50 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000203EB88E420>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 03:56:51 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000203EB88E600>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 03:56:52 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000203EB88E7E0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 03:57:15 PM - INFO - root : Login successfully
06/04/2024 03:57:41 PM - INFO - root : Started Search validation functionality
06/04/2024 03:57:53 PM - INFO - root : validated search field successfully completed
06/04/2024 03:57:56 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000203EB88F140>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 03:57:57 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000203EB88FB00>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 03:57:58 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000203EB88F8C0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 03:58:28 PM - INFO - root : Login successfully
06/04/2024 03:58:58 PM - INFO - root : Started Search page validation functionality
06/04/2024 03:59:48 PM - INFO - root : Search by meals successfully completed
06/04/2024 03:59:51 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000203EB8AC0B0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 03:59:52 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000203EB8ACB90>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 03:59:53 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000203EB8ACCE0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 03:59:56 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000203EB7FB4A0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:00:16 PM - INFO - root : Login successfully
06/04/2024 04:00:42 PM - INFO - root : Validating search page with ingredients
06/04/2024 04:00:56 PM - INFO - root : Search by ingredients functionality successfully completed
06/04/2024 04:00:59 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000203EB8AD3D0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:01:00 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000203EB8AD5B0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:01:01 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000203EB8AD790>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:01:12 PM - INFO - root : Starting the test_login_invalid_data_functionality
06/04/2024 04:10:42 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001983B2C63F0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:10:43 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001983B2C6C30>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:10:44 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001983B2C7AA0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:10:54 PM - INFO - root : Starting the test_login_valid_data_functionality
06/04/2024 04:10:57 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001983B306720>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:10:58 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001983B306870>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:10:59 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001983B3069F0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:11:09 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001983B3806E0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:11:10 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001983B3808C0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:11:11 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001983B380AA0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:11:24 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001983B382480>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:11:25 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001983B382690>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:11:26 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001983B382870>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:11:37 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001983B3B4590>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:11:38 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001983B3B4770>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:11:39 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001983B3B4950>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:11:48 PM - INFO - root : Starting the test_login_invalid_data_functionality
06/04/2024 04:14:16 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F6280C6B10>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:14:17 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F6280C6990>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:14:18 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F6280C7FE0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:14:28 PM - INFO - root : Starting the test_login_valid_data_functionality
06/04/2024 04:14:30 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F628132990>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:14:31 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F628132B40>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:14:32 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F628132CC0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:14:43 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F62816C620>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:14:44 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F62816C800>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:14:45 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F62816CA10>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:15:04 PM - INFO - root : Login successfully
06/04/2024 04:15:31 PM - INFO - root : Started Search page validation functionality
06/04/2024 04:16:21 PM - INFO - root : Search by meals successfully completed
06/04/2024 04:16:24 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F628130140>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:16:25 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F628131D60>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:16:26 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F628131250>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:16:39 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F62816E450>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:16:40 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F62816F1A0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:16:41 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F62816F380>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:16:51 PM - INFO - root : Starting the test_login_invalid_data_functionality
06/04/2024 04:19:00 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021310EC7680>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:19:01 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021310EC7CE0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:19:02 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021310F202C0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:19:12 PM - INFO - root : Starting the test_login_valid_data_functionality
06/04/2024 04:19:23 PM - INFO - root : Login successfully
06/04/2024 04:19:57 PM - INFO - root : Logout successfully
06/04/2024 04:20:00 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021310EC72C0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:20:01 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021310EC7290>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:20:02 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021310EC7CE0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:20:05 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021310F21D90>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:20:27 PM - INFO - root : Login successfully
06/04/2024 04:20:58 PM - INFO - root : Started Search validation functionality
06/04/2024 04:21:12 PM - INFO - root : validated search field successfully completed
06/04/2024 04:21:15 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021310F23350>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:21:16 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021310F23530>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:21:17 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021310F23710>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:21:20 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021310EC6E10>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:21:21 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021310EC7680>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:21:50 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021311018350>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:21:51 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021311018530>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:21:52 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021311018710>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:22:23 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021310F210D0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:22:24 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021310F22900>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:22:25 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021310F230B0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:22:36 PM - INFO - root : Starting the test_login_invalid_data_functionality
06/04/2024 04:31:52 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000217C7A76690>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:31:53 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000217C7A76BA0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:31:54 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000217C7A77A40>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:32:02 PM - INFO - root : Starting the test_login_valid_data_functionality
06/04/2024 04:32:12 PM - INFO - root : Login successfully
06/04/2024 04:32:40 PM - INFO - root : Logout successfully
06/04/2024 04:32:43 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000217C7A743B0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:32:44 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000217C7A76540>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:32:45 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000217C7A764E0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:33:06 PM - INFO - root : Login successfully
06/04/2024 04:33:31 PM - INFO - root : Started Search validation functionality
06/04/2024 04:33:44 PM - INFO - root : validated search field successfully completed
06/04/2024 04:33:47 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000217C7ADEA20>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:33:48 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000217C7ADEC00>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:33:49 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000217C7ADEDE0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:33:52 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000217C7ADF1A0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:34:11 PM - INFO - root : Login successfully
06/04/2024 04:34:35 PM - INFO - root : Started Search page validation functionality
06/04/2024 04:35:24 PM - INFO - root : Search by meals successfully completed
06/04/2024 04:35:27 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000217C7ADF530>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:35:28 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000217C7ADF710>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:35:29 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000217C7ADF8F0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:35:32 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000217C7ADFCB0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:35:50 PM - INFO - root : Login successfully
06/04/2024 04:36:18 PM - INFO - root : Validating search page with ingredients
06/04/2024 04:36:32 PM - INFO - root : Search by ingredients functionality successfully completed
06/04/2024 04:36:35 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000217C7AFD0D0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:36:36 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000217C7AFD2B0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:36:37 PM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000217C7AFD490>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/04/2024 04:36:47 PM - INFO - root : Starting the test_login_invalid_data_functionality
06/05/2024 11:02:28 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000023076BE1640>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:02:29 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000023076C469C0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:02:30 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000023076C6CA70>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:02:33 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000023076C6DD60>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:02:34 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000023076C6DF40>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:02:35 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000023076C6E120>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:02:38 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000023076C6E570>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:02:39 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000023076C6E720>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:02:40 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000023076C6E8D0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:03:06 AM - INFO - root : Starting the test_login_valid_data_functionality
06/05/2024 11:03:24 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000023076CD9760>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:03:25 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000023076CD99A0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:03:26 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000023076CD9B20>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:16:56 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B6987D0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:16:57 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B698DA0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:16:58 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B699E20>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:17:01 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B69A060>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:17:02 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B69A210>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:17:03 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B69A3C0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:17:16 AM - INFO - root : Starting the test_login_valid_data_functionality
06/05/2024 11:17:32 AM - INFO - root : Login successfully
06/05/2024 11:18:06 AM - INFO - root : Logout successfully
06/05/2024 11:18:11 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B6980B0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:18:12 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B69B260>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:18:13 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B69BCE0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:18:16 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B69ADE0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:18:17 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B69B9B0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:18:18 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B69BA70>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:18:45 AM - INFO - root : Login successfully
06/05/2024 11:19:20 AM - INFO - root : Started Search validation functionality
06/05/2024 11:19:35 AM - INFO - root : validated search field successfully completed
06/05/2024 11:19:38 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B6F69C0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:19:39 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B676FF0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:19:40 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B63FA70>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:19:43 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B69AE10>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:20:06 AM - INFO - root : Login successfully
06/05/2024 11:20:38 AM - INFO - root : Started Search page validation functionality
06/05/2024 11:21:40 AM - INFO - root : Search by meals successfully completed
06/05/2024 11:21:43 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B6F7110>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:21:44 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B6F72F0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:21:45 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B6F74D0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:21:48 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B6F7890>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:22:13 AM - INFO - root : Login successfully
06/05/2024 11:22:30 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B7F9220>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:22:31 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B7F84A0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:22:32 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B7F9520>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:22:35 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001E45B7F98E0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:22:44 AM - INFO - root : Starting the test_login_invalid_data_functionality
06/05/2024 11:22:57 AM - INFO - root : Verifying Error message while entering invalid credentials
06/05/2024 11:39:04 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001775A2C87D0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:39:05 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001775A2C9E20>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:39:06 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001775A2C9F10>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:39:15 AM - INFO - root : Starting the test_login_valid_data_functionality
06/05/2024 11:39:35 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001775A355040>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:39:36 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001775A355220>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:39:37 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001775A355340>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:39:45 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000202D3450B00>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:39:46 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000202D34CD610>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:39:47 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000202D34CE5A0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:39:56 AM - INFO - root : Starting the test_login_valid_data_functionality
06/05/2024 11:40:06 AM - INFO - root : Login successfully
06/05/2024 11:40:31 AM - INFO - root : Logout successfully
06/05/2024 11:40:33 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000202D352CC50>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:40:34 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000202D352CE00>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:40:35 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000202D352CFE0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:40:55 AM - INFO - root : Login successfully
06/05/2024 11:41:17 AM - INFO - root : Started Search validation functionality
06/05/2024 11:41:30 AM - INFO - root : validated search field successfully completed
06/05/2024 11:41:33 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000202D352E510>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:41:34 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000202D352E6F0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:41:35 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000202D352E8D0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:41:52 AM - INFO - root : Login successfully
06/05/2024 11:42:14 AM - INFO - root : Started Search page validation functionality
06/05/2024 11:43:01 AM - INFO - root : Search by meals successfully completed
06/05/2024 11:43:03 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000202D3550050>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:43:04 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000202D3550230>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:43:05 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000202D3550410>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:43:23 AM - INFO - root : Login successfully
06/05/2024 11:43:47 AM - INFO - root : Validating search page with ingredients
06/05/2024 11:44:00 AM - INFO - root : Search by ingredients functionality successfully completed
06/05/2024 11:44:02 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000202D352C1D0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:44:03 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000202D352C050>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:44:04 AM - WARNING - urllib3.connectionpool : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000202D352C590>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
06/05/2024 11:44:14 AM - INFO - root : Starting the test_login_invalid_data_functionality
06/05/2024 11:44:24 AM - INFO - root : Verifying Error message while entering invalid credentials
